[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
    from = "/*"
    to = "https://payerset.com"
    status = 301
    force = true